### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Makiyu-py** [MenuDocs/Discord.PY-Tutorials#8]
### tl;dr - Unlicensed Repository - We Have No Permission To Use/Modify/Share Code =  Legal Risk For the People Who Uses its Code = Make a License For This Repo (and all of the others too!)

**About hundreds to thousands of people (including me) watches the videos and I've noticed that some of us (again, including me,) are re-using code from this repository without the code actually having a license (which is a big legal risk.)**

**From [choosealicense.com](https://choosealicense.com/no-permission/):**

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Thank you and sorry for the mild inconvenience MenuDocs team!

**Comment by duncte123** [comment]
All MenuDocs tutorial code basically falls under the GLWTPL

**Comment by Makiyu-py** [comment]
> All MenuDocs tutorial code basically falls under the GLWTPL

Oh, Thanks for letting me know! (about the funny license too!)
